config/routes.rb
Rails.application.routes.draw do
  resources :post_comments
  get 'pages/about'
  get 'pages/contact'
  get 'pages/resources'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :admin_users
  get 'admin_users/index'
  get 'admin_users/edit'
  get 'admin_users/new'
  get 'admin_users/show'  
  resources :categories
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  get 'home/index'
  resources :posts
  get '/about', :to =>'pages#about'  
  get '/contact',:to =>'pages#contact'
  get '/resources', :to =>'pages#resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root :to =>'home#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :category, optional: false
	belongs_to :admin_user, optional: false
	has_many :post_comments, :dependent => :destroy

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post

  validates_presence_of :name
  validates_length_of :name, :within => 2..20
  validates_presence_of :body
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  def index
  	@users = AdminUser.all
  end

  def show
    @user = AdminUser.find(params[:id])
    @name = @user.name
    @posts = @user.posts
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all

  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts.order("created_at DESC")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@posts = Post.all.order("created_at DESC")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < InheritedResources::Base

    def create
    	@post_comment = PostComment.new(post_comment_params)
    	if @post_comment.save
    		flash[:notice] = "Comment was left successfully"
    		redirect_to(@post_comment.post)
    	else
    		flash[:notice] = "Comment was not created", (@post_comment.errors)
    		redirect_to(@post_comment.post)
        end
    end

    private
        def post_comment_params
            params.require(:post_comment).permit(:name, :email, :body, :post_id, :created_at)
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
       @posts = Post.all.order("created_at DESC")
       @categories = Category.all
       # @truncated_title = @post.truncate(@post.title, :length 30)
    end
    
    def show
        @post = Post.find(params[:id])
        @post_comment = PostComment.new(:post => @post)
        @post_comments = @post.post_comments
    end
    
    def new
        @post = Post.new
        @category = Category.all
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, :notice => "Your post was saved"
        else
            render "new"
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to post_path, :notice => "Your post was updated"
        else
            render "edit"
        end     
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Your post was deleted"
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :body, :category_id, :author_id, :name)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def formatted_date(date)
		return if date.nil?
		date.strftime("%A, %-d %B")
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def limited_text(body)
		body.split('').slice(300)
	end
end

app/views/admin_users/index.html.erb
<div class = "blog-header"><h1>Contributors</h1></div>
<br>
<div class = "post">
	<ul>	
		<% @users.each do|user| %>
			<p>	
				<span class="large-text"><%= link_to user.name,user %> / <%= user.posts.count %> / </span><span class="small-text">LAST POST / <%= formatted_date user.posts.last&.created_at %> /</span>
			</p>
		<% end %>
</ul>
</div>

app/views/admin_users/show.html.erb
<div class ="blog-header"><%= @user.name %></div>
<br>
<% if @posts.each do |post| %>
<div class ="post">
<span><h3 color="#ff7a3e"><%= link_to post.category.name,post.category %> / <%= link_to post.title,post %> </h3></span>
<h4><%= raw post.byline %></h4>
    <div class="entry"><%=raw post.body.truncate(300) %></div>
    <div class = "read_more"><%=h link_to "Read more",post %></div>
	<div class="byline">
              <small><%= post.created_at.strftime("%A, %d %B @ %-l:%M%P") %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.admin_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.post_comments.count %> comments</small>

    </div>
</div>

<% end.empty? %>

	<p>Sorry, there are no posts in this category</p>
	<p><%= link_to "Back",admin_users_path %></p>

<% end %>

app/views/categories/index.html.erb
<div class = "blog-header">Tidygories</div>
<br>
<div class = "post">
	<ul>	
		<% @categories.each do|category| %>
			<p>	
				<span class="large-text"><%= link_to category.name,category %> / <%= category.posts.count %> / </span><span class="small-text">Last post <%= formatted_date category.posts.last&.created_at %></span>
			</p>
		<% end %>

</ul>
</div>

<img width="685" radius="10px" src="https://www.ofdesign.net/wp-content/uploads/images/minimalist-wooden-house-on-lake-zurich-with-clean-design-3-975517156.jpg">

app/views/categories/show.html.erb
<div class ="blog-header"><%= @category.name %></div>
<br>
<% if @posts.each do |post| %>
<div class ="post">
<h3><%= link_to post.title,post %> </h3>
<h4><%= raw post.byline %></h4>
    <div class="entry"><%=raw post.body.truncate(300) %></div>
    <div class = "read_more"><%=h link_to "Read more",post %></div>
	<div class="byline">
              <small><%= post.created_at.strftime("%A, %d %B @ %-l:%M%P") %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.admin_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.post_comments.count %> comments</small>

    </div>
</div>

<% end.empty? %>

	<p>Sorry, there are no posts in this category</p>
	<p><%= link_to "Back", categories_path %></p>

<% end %>

app/views/home/index.html.erb
<div id="body">
<span><img width="685px" src="https://files.ozbargain.com.au/n/95/267095x.jpg?h=a5140dd0"></span>
<br><br>
<div class ="blog-header">Recent Posts</div>
<br>
<% @posts.first(3).each do |post| %>
<div class ="post">
<h3><%= link_to post.title,post %> </h3>
<h4><%= raw post.byline %></h4>
    <div class="entry"><%=raw post.body.truncate(200) %></div>
    <div class = "read_more"><%=h link_to "Read more",post %></div>
	<div class="byline">
              <small><%= post.created_at.strftime("%A, %d %B @ %-l:%M%P") %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.admin_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.post_comments.count %> comments</small>
    </div>
</div>

<% end %>
</div>

app/views/layouts/application.html.erb
<HTML>

<%= render "partials/header" %>
<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" type="text/css" />
<div id="body">
  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="content">     
    <div class ="flash-message">    
          <% flash.each do |key, value| %>
        <p><%= value %></p>
        <% end %>
    </div>
        <%= yield %><!-- main view -->
<BODY>
          
          <div style="clear: both;">&nbsp;</div>
        </div>
        <%= render "partials/sidebar" %>
        <!-- end #sidebar -->
        <div style="clear: both;">&nbsp;</div>
      </div>
    </div>
  </div>
  <!-- end #page -->
  <div id="footer">
    <p>&copy; 2018, TidyMe - Tidy Blog</p>
  </div>
</div>
<!-- end #footer -->
</body>
</html>

app/views/pages/about.html.erb
<h1>About my Blog</h1>
<br>
<div class = "post">
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

</p>
</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<br>
<div class = "post">
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<h1>Resources</h1>
<br>
<div class = "post">
<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html PUBLIC>
<html>
<head>
  <title>TidyMe | Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="wrapper">
  <div id="header-wrapper">
    <div id="header"> 
      <div id="logo">
        <h1><%= link_to "The Tidy", root_path %></h1>
        <p>All about the tidy...</p>
      </div>
       <div id="menu">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Blog", posts_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Resources", resources_path %></li>
        </ul>
    </div>
    </div>
  </div>
</div>
</body>

app/views/partials/_post_comment.html.erb
<div id = "post">
   <p><i><b><%= post_comment.name %></b> said</i></p>
    <%= post_comment.body %><br><br>
    <small> on <%= post_comment.created_at.strftime("%A, %d %B @ %-l:%M%P") %></small><br><hr>
</div>

app/views/partials/_sidebar.html.erb
<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" type="text/css" />

<div id="sidebar">
    <ul>
        <!-- <li>
        	<div id="search" >
        		<input type="text" id="query" name="query" />
        		<input type="submit" id="query" name="query" />
        	</div>
            <div style="clear: both;">&nbsp;</div>
        </li> -->
        <li>
          	<h2><%= link_to "Tidygories",categories_path %></h2>
                <ul>  
            	<% Category.all.each do|category| %>
              	<li><%= link_to category.name,category %></li>
            	<% end %>
         	    </ul>
        </li>
        <li>
        	<h2><%= link_to "Blogroll", posts_path %></h2>
            	<ul>
            	<% Post.last(10).each do |post| %>
            	<li><%= link_to  truncate(post.title, :length => 30),post %></li>
            	<% end %>
            	</ul>
            <h2><%= link_to "Contributors", admin_users_path %></h2>
                <ul>
                <% AdminUser.all.each do |user| %>
                <li><%= link_to user.name,user %></li>
                <% end %>
                </ul>
        </li>                
        </li>
    </ul>
</div>

app/views/post_comments/show.html.erb
<div id = "post">
    <i><b><%= post_comment.name %></b> said</i><br>
    <%= simple_format (post_comment.body) %><br>
    <small> on <%= post_comment.created_at.strftime("%A, %d %B @ %-l:%M%P") %></small>
</div>

app/views/posts/index.html.erb
<div class = "blog-header">Blog Posts</div>
<br>
<% @posts.each do |post| %>
<div class ="post">
<span><h3 color="#ff7a3e"><%= link_to post.category.name,post.category %> / <%= link_to post.title,post %> </h3></span>
<h4><%= raw post.byline %></h4>
    <div class="entry"><%=raw post.body.truncate(300) %></div>
    <div class = "read_more"><%=h link_to "Read more",post %></div>
	<div class="byline">
              <small><%= post.created_at.strftime("%A, %d %B @ %-l:%M%P") %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.admin_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<%= post.post_comments.count %> comments</small>
    </div>
</div>

<% end %>

app/views/posts/show.html.erb
<div class = "blog-header"><%= link_to @post.category.name, category_path(@post.category) %> / <%= @post.title %></div>
<br>
<div class = "post">
<p><small>Blogged <%= @post.created_at.strftime("%A, %d %B @ %-l:%M%P") %>, by <%= @post.admin_user.name %></small></p>
<p><%=raw @post.byline %></p>
<p><%=raw @post.body %></p>
<hr>


<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %>  |  <%= link_to "Back",posts_path %></p>


<hr>

<%= form_for @post_comment do |f| %>
<%= f.hidden_field :post_id %>
<p>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :body %><br />
	<%= f.text_area :body %>
</p>
<br>
<p>
	<%= f.submit "Post Comment" %>
</p>
<% end %>

<%= render :partial => "/partials/post_comment", :collection => @post.post_comments %>
</div>